import { ChatGoogleGenerativeAI } from '@langchain/google-genai';
import { createClient } from '@supabase/supabase-js';
import { serverSupabaseClient } from '#supabase/server';

export default defineEventHandler(async (event) => {
  console.log('Received API request:', event.node.req.body);
  const { query } = await readBody(event);
  console.log('Parsed query:', query);
  if (!query) {
    console.error('Query missing or empty');
    throw createError({ statusCode: 400, message: 'Query required' });
  }

  console.log('Initializing Supabase client...');
  let supabase;
  try {
    supabase = await serverSupabaseClient(event);
    console.log('Supabase SSR client initialized:', !!supabase);
  } catch (err) {
    console.error('Supabase SSR client failed:', err.message);
    supabase = createClient(
      process.env.SUPABASE_URL || '',
      process.env.SUPABASE_KEY || ''
    );
    console.log('Fallback Supabase client initialized:', !!supabase);
  }

  const schema = {
    users: ['id', 'name', 'email', 'created_at'],
    products: ['id', 'name', 'price', 'created_at'],
  };
  console.log('Schema for RAG:', schema);

  const examples = [
    { question: 'Show all users', sql: 'SELECT * FROM users;' },
    { question: 'Find products cheaper than 100', sql: 'SELECT * FROM products WHERE price < 100;' },
  ];
  console.log('Example queries for RAG:', examples);

  console.log('Initializing Gemini LLM with model: gemini-1.5-pro');
  const llm = new ChatGoogleGenerativeAI({
    model: 'gemini-1.5-pro',
    apiKey: process.env.GOOGLE_API_KEY,
  });
  console.log('Gemini LLM initialized, API key present:', !!process.env.GOOGLE_API_KEY);

  const prompt = `
    You are an expert SQL generator. Generate a valid PostgreSQL SELECT query based on the user query, schema, and examples. Output only the SQL query, no extra text or formatting.
    User Query: ${query}
    Schema: ${JSON.stringify(schema)}
    Examples: ${JSON.stringify(examples)}
    Output:
  `;
  console.log('RAG prompt constructed:', prompt);

  console.log('Invoking Gemini to generate SQL...');
  const sqlQueryResponse = await llm.invoke(prompt);
  console.log('Gemini raw response:', sqlQueryResponse);
  const sqlQuery = typeof sqlQueryResponse.content === 'string' 
    ? sqlQueryResponse.content 
    : sqlQueryResponse.content[0]?.text || '';
  console.log('Extracted SQL query:', sqlQuery);

  if (!sqlQuery) {
    console.error('No SQL query generated by Gemini');
    throw createError({ statusCode: 500, message: 'Failed to generate SQL query' });
  }

  // Robustly clean query: remove trailing semicolon and whitespace
  const cleanSqlQuery = sqlQuery.trim().replace(/;+\s*$/, '');
  console.log('Cleaned SQL query (semicolon and whitespace removed):', cleanSqlQuery);

  console.log('Executing SQL via Supabase RPC:', cleanSqlQuery);
  const { data, error } = await supabase.rpc('execute_sql', { query: cleanSqlQuery });
  console.log('SQL execution result:', { data, error });

  if (error) {
    console.error('Supabase RPC error:', error);
    throw createError({ statusCode: 500, message: error.message });
  }

  console.log('Returning response:', { sqlQuery: cleanSqlQuery, results: data || [] });
  return { sqlQuery: cleanSqlQuery, results: data || [] };
});